CrudOperations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crud.controls')),
    # Change Password

]

crud/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    password = models.CharField(max_length=10)

crud/forms.py
from django.core import validators
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Name'}), required=True,
        max_length=50)
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': "Email"}),
        required=True, max_length=50)
    password = forms.CharField(
        widget=forms.PasswordInput(render_value=True, attrs={'class': 'form-control form-control-sm', 'placeholder': "Password"}),
        required=True, max_length=50)

    class Meta:
        model = User
        fields = ['name', 'email', 'password']

crud/views.py
from django.shortcuts import render

# Create your views here.
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from .models import User


def Base(request):
    return render(request, "base.html")


'''
def Add(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            form = UserForm()
        else:
            form = UserForm()
        da = User.objects.all()
        return render(request, 'show.html', {"form": form, "da": da})

    form = UserForm(request.POST or None)
'''


def Add(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = UserForm()
    da = User.objects.all()
    return render(request, 'show.html', {"form": form, "da": da})


def Delete(request, pk):
    if request.method == "POST":
        pi = User.objects.get(pk=pk)
        pi.delete()
    return HttpResponseRedirect("/crud/add/")

def Edit(request, pk):
    if request.method == "POST":
        pi = User.objects.get(pk=pk)
        fm = UserForm(request.POST, instance=pi)
        if fm.is_valid():
            fm.save()
    else:
     pi = User.objects.get(pk=pk)
     fm = UserForm(instance=pi)
    return render(request, 'edit.html', {"form": fm})

crud/templates/base.html
{% load static %}

<html lang="en">
<head>
  <title>MemeSV</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>


<body style="">

<div> <h2 class="text-center alert alert-success" style="margin-top:1%">Function based CRUD project</h2></div>

{% block content %}


{% endblock %}


</body>
</html>

crud/templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}





<div class="row">
    <div class="col-6 col-md-4"></div>
  <div class="col-6 col-md-4">
<h2 class="text-center alert alert-info"> Update Info</h2>
      <form method="post">
    {% csrf_token %}
  {{form.as_p }}
          <input type="submit" class="btn btn-success" value="Update">
          <a href="{% url 'add' %}" class="btn btn-info">Back to home</a>

</form>
  </div>
    <div class="col-6 col-md-4"></div>
</div>



{% endblock %}

crud/templates/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="col-6 col-md-1"></div>
  <div class="col-6 col-md-3">
      <h2 class="text-center alert alert-info"> Add new user</h2>
      <form method="post">
    {% csrf_token %}
  <p><label for="id_name">Name:</label> <input type="text" name="name" class="form-control form-control-sm" placeholder="Name" maxlength="50" required id="id_name"></p>
<p><label for="id_email">Email:</label> <input type="text" name="email" class="form-control form-control-sm" placeholder="Email" maxlength="50" required id="id_email"></p>
<p><label for="inputPassword6">Password:</label> <input type="text" name="password" class="form-control form-control-sm" id="inputPassword6" placeholder="Password" maxlength="50" required></p>
    <input type="submit" class="btn btn-success" value="Add">
</form>
  </div>



  <div class="col-12 col-md-8">

      {% if da %}

      <h2 class="text-center alert alert-info"> User Details</h2>

      <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Password</th>
    </tr>
  </thead>

          {% for k in da %}
  <tbody>
    <tr>
      <th scope="row">{{k.id}}</th>
      <td>{{ k.name }}</td>
      <td>{{ k.email }}</td>
      <td>{{ k.password }}</td>
      <td><a href="{% url 'edit' k.pk %}" class="btn btn-warning">Edit</a></td>
      <td>
          <form action="{% url 'delete' k.pk %}" method="post">
              {% csrf_token %}
              <input type="submit" class="btn btn-danger" value="Delete">
          </form>
      </td>
    </tr>
  </tbody>
          {% endfor %}
</table>
{% else %}
      <h2 class="text-center alert alert-warning"> No data</h2>
 {% endif %}




  </div>

</div>

{% endblock %}